baseURL = "http://www.example.com/"
languageCode = "en"
theme = "ghazal"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
    title = "DE Theme"
    author = "The Real Dead Elf"
    description = "Dead Elf Collectibles Landing"
    footer = "Dead Elf was here"
    shortAbout = "Dead Elf Collectibles is here to supply all your Pokemon, Yu-Gi-Oh, Magic, and other TCG needs. Currenlty our online store is under construction come back soon to see what Dead Elf is up too."
    mainimage = "/img/DEC-Color.svg"
    profileImage = "https://i.stack.imgur.com/oI2SB.jpg?s=328&g=1"

    [params.theme]
        fontSize = "16px"
        dateFormat = "2006/01/02"
        paginateNum = 5

    [params.social]
        twitter = "#"
        email= "contact@deadelfcollectibles.com"